# Generated by Django 5.1.5 on 2025-01-21 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                ("opis", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Kategorie",
            },
        ),
        migrations.CreateModel(
            name="Ksiazka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tytul", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=200)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("opis", models.TextField()),
                ("rok_wydania", models.IntegerField()),
                ("dostepna", models.BooleanField(default=True)),
                (
                    "okladka",
                    models.ImageField(blank=True, null=True, upload_to="okladki/"),
                ),
                ("data_dodania", models.DateTimeField(auto_now_add=True)),
                (
                    "kategoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ksiazki.kategoria",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Książki",
            },
        ),
        migrations.CreateModel(
            name="Wypozyczenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_wypozyczenia", models.DateTimeField(auto_now_add=True)),
                ("data_zwrotu", models.DateTimeField(blank=True, null=True)),
                ("zatwierdzone", models.BooleanField(default=False)),
                ("uwagi", models.TextField(blank=True)),
                (
                    "czytelnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ksiazka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ksiazki.ksiazka",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wypożyczenia",
            },
        ),
    ]
