# Generated by Django 5.1.5 on 2025-01-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ksiazki", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wypozyczenie",
            name="oplata",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="wypozyczenie",
            name="przedluzenie",
            field=models.BooleanField(default=False),
        ),
    ]
